### ISSUE TITLE
Function ginv (nardl.R) not used anywhere in code

### ISSUE THREAD

**Issue by JoFAM** [zedtaha/nardl#1]
The function `ginv()` is defined in the file `nardl.R` but the function is used nowhere in the code. 

The function is a toned down (and less safe) version of the function `MASS::ginv()` by the way, and will likely cause errors or wrong results when there's only a single positive singular value due to dropping of dimensions.

**Comment by zedtaha** [comment]
@JoFAM yes !!! i will drop it now ;)

**Comment by JoFAM** [comment]
@zedtaha I forked your repository and I'm changing a few other things as well. I'll let you know when I'm done reviewing. I have a fork in which I'm changing a few things to get you on track, so if you want you can simply pull these changes in your repo. (Preferably in a devel branch or so, to avoid overwriting your previous version).

You'll see a number of other issues pop up soon, but you might want to wait to tackle them until I'm finished reviewing. You can take a look at the commits I did on the fork.

https://github.com/JoFAM/nardl/commits/master

**Comment by zedtaha** [comment]
Ok @JoFAM

**Comment by JoFAM** [comment]
Solved in commit https://github.com/JoFAM/nardl/commit/ef7f526bd72851a05ce14be9eac7917ccddaf698
