### ISSUE TITLE
lagm does not create correct lags when passed a nLags vector

### ISSUE THREAD

**Issue by JoFAM** [zedtaha/nardl#2]
In the function `nardl()` the following code is used to create lags:

```
     ldh<-lagm(as.matrix(dh),c(1:i))
      ldxp<-lagm(as.matrix(dxp),c(1:i))
      ldxn<-lagm(as.matrix(dxn),c(1:i))
```

Trying this with a standard matrix shows that this is not giving the desired result:

```
mat <- matrix(1:10,ncol = 2)
nardl:::lagm(mat, c(2:3))   
#>      _1 _1 _2 _2
#> [1,] NA NA NA NA
#> [2,]  1  6 NA NA
#> [3,]  2  7  1  6
#> [4,]  3  8  2  7
#> [5,]  4  9  3  8
```
I'd expect something with a lag 2 and a lag 3, but I get a matrix with lag 1 and lag 2

Reason is the use of the following line in `lagm`: `for(i in seq(nLags)) `. This is warned against in `?seq` as it actually means `seq_along(nLags)`.

**Comment by JoFAM** [comment]
Solved after commit https://github.com/JoFAM/nardl/commit/8d21aa23377b1debc0ee7f9af9e42a7c72dcb942

**Comment by zedtaha** [comment]
@JoFAM in the autoregressive case of lageed matrix we assume that we began lagging from the second as well that the first lag must exist to avoid autocorrelation

**Comment by JoFAM** [comment]
@zedtaha In that case I would expect a matrix with lag 1, 2 and 3. To make things more clear to remember later on, I rewrote `lagm()` so `nLags` simply takes a single value (eg 3) and then it creates lags from 1 to 3. That's the behaviour I presumed expected judging from the code in `nardl()`. Did I understand this right?

I also adapted the code of `nardl()` so the function works correctly. I've added some unit testing before to make sure I didn't mess up your calculations. I'm fairly sure I didn't (even though I currently only have a single test case from your examples).

**Comment by zedtaha** [comment]
@JoFAM good work and it will be easy for users to use the mlag function

**Comment by JoFAM** [comment]
@zedtaha is it meant to be used by the users? Because in that case it would better be in its own file, be exported and have some documentation. 

Then there's also another issue: duplicate column names are possible in R, but cause trouble. See eg:

```
x <- matrix(1:3, ncol = 3)   
colnames(x) <- c("a","a","a")
x[,"a"]                      
#> a 
#> 1
```

For a function accessible to the user, using duplicate colnames is really not a good idea. Is there a reason the columns are named as they are?

**Comment by zedtaha** [comment]
@JoFAM yes in this case its necessary to rename each lagged vars including the original name and the number of lags. And if there is an other efficient way to do that it will be helpful

**Comment by JoFAM** [comment]
@zedtaha In that case I would add column names if the matrix doesn't have them. That way you're sure you never end up with duplicate colnames.

Adapted `lagm` and unit test in commit https://github.com/JoFAM/nardl/commit/00d1ce856c422440f4a5e884ffaf17256733e545
